# Generated by Django 3.2.4 on 2021-07-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_price_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='value',
        ),
    ]
