# Generated by Django 3.2.5 on 2021-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_price_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.AddField(
            model_name='booking',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='contacts', to='store.Contact'),
        ),
    ]
