# Generated by Django 3.2.5 on 2021-07-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210715_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.AddField(
            model_name='booking',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='store.Contact'),
        ),
    ]
