# Generated by Django 3.2.5 on 2021-07-14 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210715_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contacts',
        ),
        migrations.AddField(
            model_name='booking',
            name='contacts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.variety'),
        ),
    ]
