# Generated by Django 3.2.5 on 2021-07-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210724_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
