# Generated by Django 3.2.5 on 2021-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variety_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='contacted',
            new_name='shipped',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='no address supplied', max_length=400),
        ),
        migrations.AddField(
            model_name='booking',
            name='pgp_public_address',
            field=models.TextField(default='no pgp address supplied'),
        ),
    ]
