# Generated by Django 3.2.5 on 2021-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210724_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='contact',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='xxx@xxx.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
