# Generated by Django 3.2.5 on 2021-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210724_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
